version: "3.9"

services:
  order-db:
    image: postgres:16
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
      - ./order-service/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  payment-db:
    image: postgres:16
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data
      - ./payment-service/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  payment-service:
    build: ./payment-service
    environment:
      PAYMENT_DB_DSN: postgres://postgres:postgres@payment-db:5432/payment_db?sslmode=disable
      PORT: "8082"
      GRPC_PORT: "50051"
    ports:
      - "8082:8082"   # REST (external users)
      - "50051:50051" # gRPC (inter-service)
    depends_on:
      payment-db:
        condition: service_healthy

  order-service:
    build: ./order-service
    environment:
      ORDER_DB_DSN: postgres://postgres:postgres@order-db:5432/order_db?sslmode=disable
      PAYMENT_GRPC_ADDR: payment-service:50051
      PORT: "8081"
      GRPC_PORT: "50052"
    ports:
      - "8085:8081"   # REST (external users)
      - "50052:50052" # gRPC streaming (SubscribeToOrderUpdates)
    depends_on:
      order-db:
        condition: service_healthy
      payment-service:
        condition: service_started

volumes:
  order_db_data:
  payment_db_data:
